[package]
name = "polars"
version = "0.8.0"
license = "MIT"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2021"
rust-version = "1.73.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8"
chrono = "0.4"
either = "1.8"
magnus = "0.6"
polars-core = "=0.36.2"
polars-parquet = "=0.36.2"
polars-utils = "=0.36.2"
serde_json = "1"
smartstring = "1"

[dependencies.rb-sys]
version = "0.9.98"
features = ["stable-api-compiled-fallback"]

[dependencies.polars]
version = "=0.36.2"
features = [
    "abs",
    "approx_unique",
    "arg_where",
    "asof_join",
    "avro",
    "binary_encoding",
    "concat_str",
    "cov",
    "cse",
    "csv",
    "cum_agg",
    "cumulative_eval",
    "cutqcut",
    "dataframe_arithmetic",
    "date_offset",
    "diagonal_concat",
    "diff",
    "dot_product",
    "dtype-full",
    "dynamic_group_by",
    "ewma",
    "extract_jsonpath",
    "fmt",
    "horizontal_concat",
    "interpolate",
    "ipc",
    "is_first_distinct",
    "is_in",
    "is_last_distinct",
    "is_unique",
    "json",
    "lazy",
    "lazy_regex",
    "list_count",
    "list_eval",
    "list_gather",
    "list_to_struct",
    "log",
    "meta",
    "mode",
    "moment",
    "object",
    "parquet",
    "partition_by",
    "pct_change",
    "peaks",
    "performant",
    "pivot",
    "product",
    "propagate_nans",
    "random",
    "rank",
    "range",
    "reinterpret",
    "repeat_by",
    "rle",
    "rolling_window",
    "round_series",
    "row_hash",
    "search_sorted",
    "semi_anti_join",
    "serde-lazy",
    "sign",
    "sql",
    "string_encoding",
    "string_pad",
    "string_to_integer",
    "strings",
    "timezones",
    "to_dummies",
    "top_k",
    "trigonometry",
    "unique_counts",
]

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = { version = "0.1", default-features = false }
